---
title: "2015 Results"
author: "Paweł Morgen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### 001

`aacomp(seq = "GLPRKILCAIAKKKGKCKGPLKLVCKC")` - could not find function "aacomp"
`aindex(seq = "GLPRKILCAIAKKKGKCKGPLKLVCKC")` - could not find function "aindex"
`instaindex(seq = "GLPRKILCAIAKKKGKCKGPLKLVCKC")` - could not find function "instaindex"
`md <- read.xvg(file)` - could not find function "read.xvg"
`train.rpart <- train(group~., data = training, method = "rpart", metric = "ROC", tuneLength = 10, trControl = fitControl)` - Error

Werdykt: 1

### 002

Warning: package 'tsbugs' not available (for R version 3.6.3 and 4.0.0)

Werdykt: 1

### 003

Warning: package 'sparkTable' not available (for R version 3.6.3 and 4.0.0)

Werdykt: 0

### 004

`(rdplot(y = vote, x = margin, title = "RD Plot - Senate Elections Data", y.label = "Vote Share in Election at time t+1", x.label = "Vote Share in Election at time t"))` - Nieco inny output, wykres OK
`rdbwselect(y = vote, x = margin, bwselect = "CV", cvgrid_min = 10, cvgrid_max = 80, cvplot = TRUE)` - Error: unused arguments

Werdykt: 2

### 005

`BKA(yA, yB, DatA$ProbA, DatB$ProbB, DatA$ProbB, DatB$ProbA, DatA$Domain, DatB$Domain, 0.95)` - Zamieniony miejscami Lower Bound i Upper Bound
`Compare(yA, yB, DatA$ProbA, DatB$ProbB, DatA$Domain, DatB$Domain)` - nieco inne wyniki
`CalSF(yA, yB, PiklA, PiklB, DatA$ProbB, DatB$ProbA, DatA$Domain, DatB$Domain, N_ab = 601)` - nieco inne wyniki

Werdykt: 3 (Nieznaczne różnice)

### 006

`head(val)` - inne wartości
`round(A[1:4, 1:4], 2)` - inne wartości
`head(d)` - inne wartości
`betahat.fun(val, solve(A), d)` - inne wartości
`interpolant.quick.complex(rbind(c(0.5, 0.3+0.1i)), d, val, solve(A), scales = true_scales, means = true_means, give.Z = TRUE)` - inne wartości
`head(valsigma)` - inne wartości
...
Generalnie wszystko działa, tylko z reguły zwraca nie to, co trzeba. Choć zbliżone.
Werdykt: 1

### 007
`EB$fit$summary` - nieco inny output, ale wartości się zgadzają

Werdykt: 3

### 008

Werdykt: 3

### 009
Werdykt: NA - Nie ma czego reprodukować

### 010

`plot(res.cagalt, choix = "quali.var", conf.ellip = TRUE, axes = c(1, 4))` - Error in data.frame(facteur = label, res) : 
  arguments imply differing number of rows: 0, 200
  
Werdykt: 2

### Podsumowanie

|Rating|Freq|
|-----:|:---|
|0     |1   |
|1     |3   |
|2     |2   |
|3     |3   |
|NA    |1   |